name: 'music_streaming'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'music_streaming'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Using variables for schema management
vars:
  raw_schema: 'raw'
  bronze_schema: 'bronze'
  silver_schema: 'silver'
  gold_schema: 'gold'

# Materialization defaults
models:
  music_streaming:
    +materialized: view
    bronze:
      +materialized: table
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
      +tags: ["dimension"]
    gold:
      +materialized: table
      +schema: gold
      +tags: ["gold", "analytics"]

# Snapshots configuration for SCD Type 2
snapshots:
  music_streaming:
    +target_schema: silver
    +unique_key: id
    +strategy: timestamp
    +updated_at: updated_at 