version: 2

models:
  - name: dim_users
    description: User dimension table with historical changes (SCD Type 2)
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - userKey
    columns:
      - name: userKey
        description: Surrogate key for the user dimension
        tests:
          - not_null
      - name: userId
        description: User ID from the source system
        tests:
          - not_null
      - name: firstName
        description: User's first name
      - name: lastName
        description: User's last name
      - name: gender
        description: User's gender
      - name: level
        description: User's subscription level (free/paid)
      - name: registration_time
        description: Time when the user registered
      - name: row_activation_date
        description: Date when this record became active
        tests:
          - not_null
      - name: row_expiration_date
        description: Date when this record expired (9999-12-31 for current records)
        tests:
          - not_null
      - name: current_row
        description: Flag indicating if this is the current record for the user
        tests:
          - not_null

  - name: dim_location
    description: Location dimension with geographic details
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - locationKey
    columns:
      - name: locationKey
        description: Surrogate key for the location dimension
        tests:
          - not_null
      - name: city
        description: City name
        tests:
          - not_null
      - name: stateCode
        description: State code (2 letter abbreviation)
        tests:
          - not_null
      - name: stateName
        description: Full state name
      - name: zip
        description: ZIP code
      - name: latitude
        description: Geographic latitude
      - name: longitude
        description: Geographic longitude

  - name: dim_songs
    description: Song dimension with metadata
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - songKey
    columns:
      - name: songKey
        description: Surrogate key for the song dimension
        tests:
          - not_null
      - name: songId
        description: Song ID from the source system
      - name: title
        description: Song title
        tests:
          - not_null
      - name: artistName
        description: Artist name
        tests:
          - not_null
      - name: duration
        description: Song duration in seconds
      - name: key
        description: Musical key
      - name: keyConfidence
        description: Confidence score for the musical key detection
      - name: loudness
        description: Song loudness measurement
      - name: songHotness
        description: Popularity score for the song
      - name: tempo
        description: Song tempo in BPM
      - name: year
        description: Release year

  - name: dim_artists
    description: Artist dimension with details
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - artistKey
    columns:
      - name: artistKey
        description: Surrogate key for the artist dimension
        tests:
          - not_null
      - name: artistId
        description: Artist ID from the source system
      - name: name
        description: Artist name
        tests:
          - not_null
      - name: location
        description: Artist's location or origin
      - name: latitude
        description: Geographic latitude of artist's location
      - name: longitude
        description: Geographic longitude of artist's location

  - name: dim_datetime
    description: Date and time dimension for time-based analysis
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - dateKey
    columns:
      - name: dateKey
        description: Surrogate key for the datetime dimension
        tests:
          - not_null
      - name: datetime
        description: Date and time at hourly granularity
        tests:
          - not_null
      - name: dayOfWeek
        description: Day of week (1-7)
      - name: dayOfMonth
        description: Day of month (1-31)
      - name: dayOfYear
        description: Day of year (1-366)
      - name: month
        description: Month (1-12)
      - name: year
        description: Year
      - name: weekendFlag
        description: Flag indicating if the date is a weekend 