version: 2

models:
  - name: fact_stream
    description: "Fact table connecting users, songs, artists, locations and time dimensions"
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1
    columns:
      - name: userKey
        description: "Foreign key to dim_users"
      - name: songKey
        description: "Foreign key to dim_songs"
      - name: artistKey
        description: "Foreign key to dim_artists"
      - name: locationKey
        description: "Foreign key to dim_location"
      - name: dateKey
        description: "Foreign key to dim_datetime"
      - name: timestamp
        description: "Original event timestamp"
        tests:
          - not_null
      - name: date_part
        description: "Date component for partitioning"
  
  - name: wide_fact
    description: "Denormalized view of the fact table joined with dimensions"
    columns:
      - name: userKey
        description: "User dimension key"
      - name: firstName
        description: "User's first name"
      - name: lastName
        description: "User's last name"
      - name: gender
        description: "User's gender"
      - name: level
        description: "User's subscription level"
      - name: userId
        description: "Original user ID"
      - name: songName
        description: "Song title"
      - name: artistName
        description: "Artist name"
      - name: songDuration
        description: "Song duration in seconds"
      - name: city
        description: "City name"
      - name: state
        description: "State code"
      - name: dateHour
        description: "Hour granularity datetime"
      - name: dayOfWeek
        description: "Day of week (1-7)"
      - name: dayOfMonth
        description: "Day of month (1-31)"

  - name: daily_user_summary
    description: "Daily aggregation of user metrics"
    columns:
      - name: date_part
        description: "Date"
        tests:
          - not_null
      - name: userId
        description: "User ID"
        tests:
          - not_null
      - name: firstName
        description: "User's first name"
      - name: lastName
        description: "User's last name" 
      - name: level
        description: "User's subscription level"
      - name: total_streams
        description: "Total number of streams by the user on this date"
      - name: unique_songs
        description: "Number of unique songs played by the user on this date"
      - name: unique_artists
        description: "Number of unique artists played by the user on this date"

  - name: daily_location_summary
    description: "Daily aggregation of location metrics"
    columns:
      - name: date_part
        description: "Date"
        tests:
          - not_null
      - name: city
        description: "City name"
        tests:
          - not_null
      - name: state
        description: "State code"
        tests:
          - not_null
      - name: total_streams
        description: "Total number of streams from this location on this date"
      - name: unique_users
        description: "Number of unique users from this location on this date"
      - name: unique_songs
        description: "Number of unique songs played from this location on this date"

  - name: artist_popularity
    description: "Artist popularity metrics"
    columns:
      - name: artistName
        description: "Artist name"
        tests:
          - not_null
      - name: total_streams
        description: "Total number of streams for this artist"
      - name: unique_users
        description: "Number of unique users who listened to this artist"
      - name: unique_songs
        description: "Number of unique songs by this artist that were played"
      - name: active_days
        description: "Number of days this artist was listened to" 