apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: broker
    broker-id: "1"
spec:
  type: LoadBalancer
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: broker
    statefulset.kubernetes.io/pod-name: kafka-broker-1 