global:
  storageClass: "default"

kraft:
  enabled: false

controller:
  replicaCount: 0
  automountServiceAccountToken: true

zookeeper:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

listeners:
  client:
    protocol: PLAINTEXT
    name: CLIENT
  interbroker:
    protocol: PLAINTEXT
    name: INTERNAL

broker:
  replicaCount: 2
  heapOpts: "-Xmx1024m -Xms1024m"
  automountServiceAccountToken: true
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  extraConfig: |
    offsets.topic.replication.factor=2
    offsets.topic.num.partitions=50
    offsets.topic.segment.bytes=104857600
    offsets.topic.compression.codec=0
    offsets.retention.minutes=10080
    offsets.retention.check.interval.ms=600000
    inter.broker.listener.name=INTERNAL

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    enabled: false

rbac:
  create: true

service:
  type: LoadBalancer
  ports:
    client: 9092
    internal: 9094

# Let's use a simpler approach - create a separate service for broker 1
externalAccess:
  enabled: false