global:
  storageClass: "default"

kraft:
  enabled: false

controller:
  replicaCount: 0

zookeeper:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

listeners:
  client:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT

broker:
  replicaCount: 2
  heapOpts: "-Xmx1024m -Xms1024m"
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  extraConfig: |
    offsets.topic.replication.factor=2
    offsets.topic.num.partitions=50
    offsets.topic.segment.bytes=104857600
    offsets.topic.compression.codec=0
    offsets.retention.minutes=10080
    offsets.retention.check.interval.ms=600000

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    enabled: false