global:
  storageClass: "default"

persistence:
  enabled: true
  storageClass: "default"

zookeeper:
  enabled: true
  persistence:
    enabled: true
    storageClass: "default"
  replicaCount: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

kraft:
  enabled: false

controller:
  replicaCount: 0
  automountServiceAccountToken: true

listeners:
  client:
    protocol: PLAINTEXT
    name: EXTERNAL
  interbroker:
    protocol: PLAINTEXT
    name: INTERNAL

broker:
  replicaCount: 1
  heapOpts: "-Xmx256m -Xms256m"
  automountServiceAccountToken: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  extraConfig: |
    offsets.topic.replication.factor=1
    offsets.topic.num.partitions=50
    offsets.topic.segment.bytes=104857600
    offsets.topic.compression.codec=0
    offsets.retention.minutes=10080
    offsets.retention.check.interval.ms=600000
    # Configure listeners
    listeners=INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
    listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    inter.broker.listener.name=INTERNAL
    # Simplified advertised listeners for single broker
    advertised.listeners=INTERNAL://kafka-broker-0.kafka-broker-headless.kafka.svc.cluster.local:9093,EXTERNAL://4.156.34.27:9092

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    enabled: false

rbac:
  create: true

service:
  type: LoadBalancer
  ports:
    client: 9092
    internal: 9093

# Disable external access through the chart's mechanism
externalAccess:
  enabled: false